#ifndef COMMONDEFINE_GLOBAL_H
#define COMMONDEFINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONDEFINE_LIBRARY)
#  define COMMONDEFINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONDEFINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONDEFINE_GLOBAL_H
